server:
  port: 8060   

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: client-service
  liquibase:
      enabled: true
      change-log: classpath:/db/liquibase-changelog.xml

  datasource:
    url:      'jdbc:postgresql://localhost:5432/client'
    username: 'client_account'
    password: 'client_account'
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'        
  banner:
    location: 'classpath:/banner.txt'

